// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

Texture2D input_tex;
// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float3> result;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    // TODO: insert actual code here!
    float3 input = input_tex[id.xy];
    
    result[id.xy] = float3(input.r, input.g, input.b);
}
